
# This file was *autogenerated* from the file ecc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3)# set_random_seed(1234567)
bits = _sage_const_100 
P = random_prime(_sage_const_2 **bits-_sage_const_1 ,True,_sage_const_2 **(bits-_sage_const_1 ))

x = ZZ.random_element(P)
y = ZZ.random_element(P)
A = ZZ.random_element(P)

R = Integers(P)
B = R(y**_sage_const_2  - x**_sage_const_3  - A*x)

ECC = EllipticCurve(R,[A,B])
G = ECC(x,y)
G_order = G.order()
GR = Integers(G_order)

k = Integer(GR(ZZ.random_element(P)))
kG = k*G

print "P =", P
print "A =", A
print "B =", B
print "G = " + "(" + str(G[_sage_const_0 ]) + "," + str(G[_sage_const_1 ]) + ")"
print "kG = " + "(" + str(kG[_sage_const_0 ]) + "," + str(kG[_sage_const_1 ]) + ")"

print "order =", G_order
print "k =", k



