
# This file was *autogenerated* from the file ecc_solution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1136909012913895610619299 = Integer(1136909012913895610619299); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_916111890075709280798539 = Integer(916111890075709280798539); _sage_const_97108866468899398617789 = Integer(97108866468899398617789); _sage_const_1049529962351829133028442 = Integer(1049529962351829133028442); _sage_const_417925137413854092364323 = Integer(417925137413854092364323); _sage_const_926978017941551607526856 = Integer(926978017941551607526856); _sage_const_947568670657555140669246 = Integer(947568670657555140669246)
P = _sage_const_1136909012913895610619299 
A = _sage_const_1049529962351829133028442 
B = _sage_const_417925137413854092364323 
G = (_sage_const_947568670657555140669246 , _sage_const_97108866468899398617789 )
kG= (_sage_const_926978017941551607526856 , _sage_const_916111890075709280798539 )

E = EllipticCurve(Integers(P),[A,B])
GG = E(G[_sage_const_0 ],G[_sage_const_1 ])
kGG = E(kG[_sage_const_0 ],kG[_sage_const_1 ])

k = GG.discrete_log(kGG)
print k*GG
print k

